import { useNavigate, useParams } from 'react-router-dom';
import { useForm } from 'react-hook-form';
import { PageHeader } from '@/components/ui/PageHeader';
import { Button } from '@/components/ui/Button';
import { Loading } from '@/components/ui/Loading';
import { ErrorState } from '@/components/ui/ErrorState';
import { useMultiplier, useSaveMultiplier } from '@/features/multipliersApi';
import { Block, BlockConnector, StickyBottomBar } from '@/features/rules/components/RuleBlocks';
export default function MultiplierEditorPage(){const {id}=useParams(); const isNew=!id||id==='nuevo'; const q=useMultiplier(isNew?null:id!); const save=useSaveMultiplier(); const nav=useNavigate(); const {register,handleSubmit}=useForm({values:q.data,defaultValues:{name:'Nuevo multiplicador',description:'factor de bonificación',factor:1.5,kind:'permanent',active:true}}); if(!isNew&&q.isLoading)return <Loading label="Cargando multiplicador..."/>; if(q.isError)return <ErrorState onRetry={()=>q.refetch()}/>; const submit=handleSubmit(async(v)=>{await save.mutateAsync({...v,id:isNew?undefined:id});nav('/multiplicadores')});return <><PageHeader title={isNew?'Nuevo multiplicador':q.data?.name??'Multiplicador'} subtitle="configurá identidad, condiciones, programación y tope"/><div className="max-w-3xl"><Block num={1} kind="multiplier" kindLabel="identidad" title="nombre y factor"><div className="grid gap-4"><input className="field" {...register('name')}/><input className="field" {...register('description')}/><input type="number" step="0.1" className="field" {...register('factor')}/></div></Block><BlockConnector/><Block num={2} kind="condition" kindLabel="condiciones" title="cuándo aplica"><div className="grid grid-cols-3 gap-2"><input className="field" defaultValue="player.vip_tier"/><select className="field"><option>eq</option><option>in</option></select><input className="field" defaultValue="gold"/></div></Block><BlockConnector/><Block num={3} kind="trigger" kindLabel="programación" title="vigencia"><select className="field" {...register('kind')}><option value="permanent">permanente</option><option value="temporary">temporal</option><option value="event">evento</option></select></Block></div><StickyBottomBar onCancel={()=>nav('/multiplicadores')} onSaveDraft={submit} onActivate={submit} loading={save.isPending}/></>}
