import { Plus, Upload } from 'lucide-react';
import { useNavigate, useSearchParams } from 'react-router-dom';
import { Button } from '@/components/ui/Button';
import { EmptyState } from '@/components/ui/EmptyState';
import { ErrorState } from '@/components/ui/ErrorState';
import { FilterPill } from '@/components/ui/FilterPill';
import { Loading } from '@/components/ui/Loading';
import { PageHeader } from '@/components/ui/PageHeader';
import { SearchInput } from '@/components/ui/SearchInput';
import { StatCard } from '@/components/ui/StatCard';
import { Toolbar } from '@/components/ui/Toolbar';
import { useAchievements } from '@/features/tier3Api';
import type { Achievement } from '@/types/tier3';
import type { Tier } from '@/types/shared';
const tiers:Tier[]=['bronze','silver','gold','platinum','diamond']; const cfg:Record<Tier,{label:string;emoji:string;color:string}>={bronze:{label:'BRONZE',emoji:'🥉',color:'text-orange'},silver:{label:'SILVER',emoji:'🥈',color:'text-text-secondary'},gold:{label:'GOLD',emoji:'🥇',color:'text-gold'},platinum:{label:'PLATINUM',emoji:'🏆',color:'text-text-primary'},diamond:{label:'DIAMOND',emoji:'💎',color:'text-info'}};
export default function AchievementsPage(){const [params,setParams]=useSearchParams(); const mock=params.get('mockState'); const filter=(params.get('tier') as Tier|'all')??'all'; const q=useAchievements(); const nav=useNavigate(); const data=mock==='empty'?[]:(q.data??[]); const visibleTiers=filter==='all'?tiers:[filter]; return <><PageHeader title="Logros" subtitle="trofeos permanentes que tus jugadores desbloquean" actions={<><Button icon={<Upload size={14}/>}>importar</Button><Button variant="primary" icon={<Plus size={14}/>} onClick={()=>nav('/logros/nuevo')}>nuevo logro</Button></>}/><div className="mb-7 grid grid-cols-4 gap-4 max-md:grid-cols-2"><StatCard label="total" value={data.length}/><StatCard label="publicados" value={data.filter(a=>a.status==='active').length}/><StatCard label="desbloqueos 7d" value="1.847" trend={{value:'+8.2%',direction:'up'}}/><StatCard label="tasa global" value="42.8%"/></div><Toolbar search={<SearchInput placeholder="buscar logro..."/>} filters={<><FilterPill label="todos" count={data.length} active={filter==='all'} onClick={()=>setParams({})}/>{tiers.map(t=><FilterPill key={t} label={t} count={data.filter(a=>a.tier===t).length} active={filter===t} onClick={()=>setParams({tier:t})}/>)}</>}/>{(mock==='loading'||q.isLoading)&&<Loading label="Cargando logros..."/>}{(mock==='error'||q.isError)&&<ErrorState onRetry={()=>q.refetch()}/>} {mock!=='loading'&&mock!=='error'&&!q.isLoading&&!q.isError&&data.length===0&&<EmptyState title="No hay logros" description="Creá medallas permanentes para el perfil del jugador."/>} {data.length>0&&visibleTiers.map(t=><TierGrid key={t} tier={t} achievements={data.filter(a=>a.tier===t)} onAdd={()=>nav(`/logros/nuevo?tier=${t}`)}/>)}</>}
function TierGrid({tier,achievements,onAdd}:{tier:Tier;achievements:Achievement[];onAdd:()=>void}){const c=cfg[tier]; return <section className="mb-8"><h3 className={`label-section mb-4 flex items-center gap-2 ${c.color}`}><span>{c.emoji}</span>{c.label} · {achievements.length} logros</h3><div className="grid grid-cols-6 gap-3 max-[1200px]:grid-cols-4 max-md:grid-cols-2">{achievements.map(a=><button key={a.id} className="aspect-square rounded-xl border border-border-subtle bg-bg-secondary p-4 text-left transition hover:border-accent/30"><div className="mb-3 text-[34px]">{a.iconKey}</div><div className="font-semibold">{a.name}</div><p className="line-clamp-2 text-[11px] text-text-tertiary">{a.description}</p><div className="mt-3 text-[12px] text-accent">{a.unlockRatePercent}%</div></button>)}<button onClick={onAdd} className="flex aspect-square flex-col items-center justify-center rounded-xl border-2 border-dashed border-border-default text-text-tertiary hover:border-accent hover:text-accent"><Plus/><span className="text-[11px]">agregar logro</span></button></div></section>}
