import { ExternalLink, MoreVertical, Pin, Plus } from 'lucide-react';
import { useSearchParams } from 'react-router-dom';
import { Button } from '@/components/ui/Button';
import { EmptyState } from '@/components/ui/EmptyState';
import { ErrorState } from '@/components/ui/ErrorState';
import { IconButton } from '@/components/ui/IconButton';
import { Loading } from '@/components/ui/Loading';
import { PageHeader } from '@/components/ui/PageHeader';
import { StatCard } from '@/components/ui/StatCard';
import { formatRelativeDate } from '@/lib/format';
import { useNews, useTogglePin } from '@/features/tier4Api';
import type { NewsItem } from '@/types/tier4';
export default function NewsPage(){const [params]=useSearchParams(); const mock=params.get('mockState'); const q=useNews(); const items=mock==='empty'?[]:(q.data??[]); const pinned=items.filter(n=>n.pinned); const others=items.filter(n=>!n.pinned); return <><PageHeader title="Noticias y novedades" subtitle='contenido persistente que tus jugadores ven en la sección "novedades" del widget' actions={<Button variant="primary" icon={<Plus size={14}/>}>publicar noticia</Button>}/><div className="mb-7 grid grid-cols-4 gap-4 max-md:grid-cols-2"><StatCard label="publicadas" value={items.filter(n=>n.status==='published').length}/><StatCard label="views totales" value="84.720" trend={{value:'+12%',direction:'up'}}/><StatCard label="CTR promedio" value="14.2%"/><StatCard label="borradores" value={items.filter(n=>n.status==='draft').length}/></div>{mock==='empty'&&items.length===0&&<EmptyState title="No hay noticias" description="Publicá contenido persistente para el widget."/>}{(mock==='loading'||q.isLoading)&&<Loading label="Cargando noticias..."/>}{(mock==='error'||q.isError)&&<ErrorState onRetry={()=>q.refetch()}/>} {mock!=='empty'&&mock!=='loading'&&mock!=='error'&&!q.isLoading&&!q.isError&&items.length===0&&<EmptyState title="No hay noticias" description="Publicá contenido persistente para el widget."/>}{items.length>0&&<><section className="mb-7"><h3 className="label-section mb-3">📌 Pinned · {pinned.length}</h3><div className="space-y-2">{pinned.map(n=><NewsRow key={n.id} item={n}/>)}</div></section><section><h3 className="label-section mb-3">Todas las noticias</h3><div className="space-y-2">{others.map(n=><NewsRow key={n.id} item={n}/>)}</div></section></>}</>}
function NewsRow({item}:{item:NewsItem}){const pin=useTogglePin(); return <div className={`card grid grid-cols-[160px_1fr_180px] overflow-hidden max-md:grid-cols-1 ${item.pinned?'border-gold/30':''}`}><div className="relative aspect-video bg-bg-tertiary"><img src={item.bannerUrl??'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=800'} alt="" loading="lazy" className="h-full w-full object-cover"/>{item.pinned&&<span className="absolute left-2 top-2 rounded bg-gold px-2 py-0.5 text-[12px] font-semibold text-text-onAccent">anclado</span>}</div><div className="p-4"><div className="mb-1 flex gap-2 text-[13px] text-text-tertiary"><span>{item.status}</span><span>·</span><span>{formatRelativeDate(item.publishedAt)}</span></div><h3 className="font-semibold">{item.title}</h3><p className="line-clamp-2 text-[14px] text-text-tertiary">{item.subtitle}</p>{item.cta&&<p className="mt-2 text-[13px] text-accent">CTA: {item.cta.label} →</p>}</div><div className="flex flex-col justify-between border-l border-border-subtle p-4"><div className="grid grid-cols-2 gap-3"><div><div className="label-section">vistas</div><b>{item.views.toLocaleString('es-AR')}</b></div><div><div className="label-section">CTR</div><b className="text-success">{item.ctrPercent}%</b></div></div><div className="flex justify-end gap-1"><IconButton icon={Pin} title="pin" active={item.pinned} onClick={()=>pin.mutate(item.id)}/><IconButton icon={ExternalLink} title="ver"/><IconButton icon={MoreVertical} title="más"/></div></div></div>}
