import { useEditor, EditorContent } from '@tiptap/react';
import StarterKit from '@tiptap/starter-kit';
import { useNavigate, useParams } from 'react-router-dom';
import { Button } from '@/components/ui/Button';
import { PageHeader } from '@/components/ui/PageHeader';
import { ConfiguratorScaffold, ConfigSection } from '@/components/configurator/ConfiguratorScaffold';
import { StickyBottomBar } from '@/features/rules/components/RuleBlocks';
import { useNewsItem, useSaveNews } from '@/features/tier4Api';
export default function NewsEditorPage(){const {id}=useParams(); const isNew=!id||id==='nueva'; const q=useNewsItem(isNew?null:id!); const save=useSaveNews(); const nav=useNavigate(); const editor=useEditor({extensions:[StarterKit],content:q.data?.bodyHtml??'<p>Escribí la noticia para tus jugadores...</p>'}); const submit=async(status:'draft'|'published')=>{await save.mutateAsync({id:isNew?undefined:id,title:(document.querySelector<HTMLInputElement>('#news-title')?.value)||'Nueva noticia',bodyHtml:editor?.getHTML()??'',publishedAt:status==='published'?new Date().toISOString():null,pinned:false,targeting:{allPlayers:true},status,views:0,clicksOnCta:0,ctrPercent:0}); nav('/noticias')};return <><PageHeader title={isNew?'Nueva noticia':q.data?.title??'Noticia'} subtitle="contenido persistente para la sección novedades del widget"/><ConfiguratorScaffold><ConfigSection title="Contenido" icon="📰"><input id="news-title" className="field" defaultValue={q.data?.title??'Nueva noticia'} /><input className="field" placeholder="subtítulo" defaultValue={q.data?.subtitle}/><div className="rounded-lg border border-border-default bg-bg-tertiary p-3"><div className="mb-2 flex gap-2"><Button size="sm" onClick={()=>editor?.chain().focus().toggleBold().run()}>bold</Button><Button size="sm" onClick={()=>editor?.chain().focus().toggleItalic().run()}>italic</Button></div><EditorContent editor={editor} className="min-h-40 rounded bg-bg-secondary p-3 text-[15px]"/></div></ConfigSection><ConfigSection title="Publicación" icon="📌"><label className="flex items-center gap-2"><input type="checkbox"/> pinear arriba</label><input type="datetime-local" className="field"/></ConfigSection><ConfigSection title="Call to action" icon="➡️"><input className="field" placeholder="texto botón"/><input className="field" placeholder="deep link"/></ConfigSection></ConfiguratorScaffold><StickyBottomBar onCancel={()=>nav('/noticias')} onSaveDraft={()=>submit('draft')} onActivate={()=>submit('published')} loading={save.isPending}/></>}
