import { Plus } from 'lucide-react';
import { useState } from 'react';
import { useSearchParams } from 'react-router-dom';
import { Button } from '@/components/ui/Button';
import { EmptyState } from '@/components/ui/EmptyState';
import { ErrorState } from '@/components/ui/ErrorState';
import { Loading } from '@/components/ui/Loading';
import { Modal } from '@/components/ui/Modal';
import { PageHeader } from '@/components/ui/PageHeader';
import { StatCard } from '@/components/ui/StatCard';
import { Table, type Column } from '@/components/ui/Table';
import { useEnabledCategories } from '@/features/settingsApi';
import { useLeaderboard, useRankings, useSaveRanking, useToggleRanking } from '@/features/rankingsApi';
import { formatNumber } from '@/lib/format';
import type { LeaderboardEntry, PrizeRow, Ranking } from '@/types/expandedTier5';
export default function RankingsPage(){const [params]=useSearchParams(); const mock=params.get('mockState'); const q=useRankings(); const enabled=useEnabledCategories(); const [tab,setTab]=useState<'active'|'available'|'history'>('active'); const [config,setConfig]=useState<Ranking|null>(null); const [leader,setLeader]=useState<Ranking|null>(null); const rows=(mock==='empty'?[]:(q.data??[])).filter(r=>!r.requires_category||enabled.includes(r.requires_category)); const active=rows.filter(r=>r.active); const available=rows.filter(r=>!r.active); const visible=tab==='active'?active:tab==='available'?available:[]; if(mock==='loading'||q.isLoading)return <Loading label="Cargando rankings..."/>; if(mock==='error'||q.isError)return <ErrorState onRetry={()=>q.refetch()}/>; if(mock==='empty')return <EmptyState title="No hay rankings" description="Activá uno de los rankings predefinidos."/>; return <><PageHeader title="Ranking" subtitle="leaderboards continuos con métricas predefinidas"/><div className="mb-7 grid grid-cols-4 gap-4 max-md:grid-cols-2"><StatCard label="rankings activos" value={`${active.length} / ${rows.length}`}/><StatCard label="jugadores compitiendo" value={formatNumber(active.reduce((s,r)=>s+r.current_participants,0))}/><StatCard label="premios distribuidos" value="2.4M"/><StatCard label="top performer" value="@tigre_loco_82"/></div><div className="mb-5 flex gap-2"><Button variant={tab==='active'?'primary':'secondary'} onClick={()=>setTab('active')}>Activos · {active.length}</Button><Button variant={tab==='available'?'primary':'secondary'} onClick={()=>setTab('available')}>Disponibles · {available.length}</Button><Button variant={tab==='history'?'primary':'secondary'} onClick={()=>setTab('history')}>Histórico</Button></div>{tab==='history'?<EmptyState title="Histórico de cierres" description="Los cierres pasados aparecerán cuando haya rankings finalizados."/>:<div className="space-y-3">{visible.map(r=><RankingCard key={r.id} ranking={r} onConfig={()=>setConfig(r)} onLeaderboard={()=>setLeader(r)}/>)}</div>}{leader&&<Leaderboard ranking={leader} onClose={()=>setLeader(null)}/>}<RankingConfigModal ranking={config} onClose={()=>setConfig(null)}/></>}
function RankingCard({ranking,onConfig,onLeaderboard}:{ranking:Ranking;onConfig:()=>void;onLeaderboard:()=>void}){const toggle=useToggleRanking();return <div className="card grid grid-cols-[64px_1fr_auto] items-center gap-4 p-4 max-md:grid-cols-1"><div className="flex h-14 w-14 items-center justify-center rounded-xl bg-bg-tertiary text-2xl">{ranking.icon}</div><div><div className="flex gap-2"><b>{ranking.name}</b><span className={`rounded-full px-2 py-0.5 text-[10px] ${ranking.active?'bg-success/15 text-success':'bg-bg-tertiary text-text-tertiary'}`}>{ranking.active?'activo':'disponible'}</span></div><p className="text-[12px] text-text-tertiary">{ranking.description}</p><p className="mt-1 text-[11px] text-text-secondary">{ranking.window} · {ranking.visibility} · {formatNumber(ranking.current_participants)} jugadores · cierra {new Date(ranking.closes_at).toLocaleDateString('es-AR')}</p></div><div className="flex gap-2"><Button onClick={()=>toggle.mutate({id:ranking.id,active:!ranking.active})}>{ranking.active?'desactivar':'activar'}</Button><Button onClick={onConfig}>Configurar</Button>{ranking.active&&<Button variant="primary" onClick={onLeaderboard}>Ver leaderboard</Button>}</div></div>}
function RankingConfigModal({ranking,onClose}:{ranking:Ranking|null;onClose:()=>void}){const save=useSaveRanking(); const [prizes,setPrizes]=useState<PrizeRow[]>(ranking?.prizes??[]); if(!ranking)return null; const max=Math.max(0,...prizes.map(p=>p.position_to)); const add=()=>max<20&&setPrizes([...prizes,{position_label:`#${max+1}`,position_from:max+1,position_to:max+1,amount:5000,prize_type:'coins'}]); return <Modal open onClose={onClose} title={`Configurar ${ranking.name}`} footer={<><Button onClick={onClose}>Cancelar</Button><Button variant="primary" onClick={()=>{save.mutate({...ranking,prizes});onClose()}}>Guardar configuración</Button></>}><div className="space-y-4"><div><p className="label-section mb-2">Ventana de tiempo</p><div className="flex gap-2">{['daily','weekly','monthly','all_time'].map(w=><Button key={w} variant={ranking.window===w?'primary':'secondary'}>{w}</Button>)}</div></div><div><p className="label-section mb-2">Premios al top</p>{prizes.map((p,i)=><div key={i} className="mb-2 grid grid-cols-[80px_1fr_160px] gap-2"><input className="field" value={p.position_label} readOnly/><input className="field" defaultValue={p.amount}/><select className="field" defaultValue={p.prize_type}><option>coins</option><option>coins_plus_chest</option><option>coins_plus_multiplier</option><option>xp_boost</option></select></div>)}<Button disabled={max>=20} icon={<Plus size={13}/>} onClick={add}>Agregar fila</Button>{max>=20&&<p className="mt-2 text-[11px] text-warning">máximo 20 posiciones premiables</p>}</div></div></Modal>}
function Leaderboard({ranking,onClose}:{ranking:Ranking;onClose:()=>void}){const q=useLeaderboard(ranking.id); const cols:Column<LeaderboardEntry>[]=[{key:'pos',header:'pos',render:e=>e.position<=3?['🥇','🥈','🥉'][e.position-1]:e.position},{key:'player',header:'jugador',render:e=><span>{e.player_handle} {e.verified?'✓':''}</span>},{key:'metric',header:ranking.metric_label,render:e=>formatNumber(e.metric_value)},{key:'change',header:'cambio',render:e=>e.change===null?<span className="text-info">NEW</span>:e.change>0?<span className="text-success">↑ {e.change}</span>:e.change<0?<span className="text-danger">↓ {Math.abs(e.change)}</span>:'='},{key:'vip',header:'VIP',render:e=>e.vip_tier??'—'}];return <div className="mt-6"><div className="mb-3 flex items-center justify-between"><div><h2 className="text-lg font-semibold">{ranking.name} · top 20</h2><p className="text-[12px] text-text-tertiary">Actualizado hace 3 min · cierra {new Date(ranking.closes_at).toLocaleString('es-AR')}</p></div><Button onClick={onClose}>Cerrar</Button></div><Table columns={cols} rows={q.data?.entries??[]} rowKey={e=>String(e.position)}/></div>}
