import { Copy, Crown, Gift, Plus } from 'lucide-react';
import { useState } from 'react';
import { useSearchParams } from 'react-router-dom';
import { Button } from '@/components/ui/Button';
import { EmptyState } from '@/components/ui/EmptyState';
import { ErrorState } from '@/components/ui/ErrorState';
import { Loading } from '@/components/ui/Loading';
import { Modal } from '@/components/ui/Modal';
import { PageHeader } from '@/components/ui/PageHeader';
import { StatCard } from '@/components/ui/StatCard';
import { StickyBottomBar } from '@/features/rules/components/RuleBlocks';
import { useCycles, useSaveCycle } from '@/features/tier3Api';
import type { DayReward, RewardsCycle } from '@/types/tier3';
export default function DailyRewardsPage(){const [params]=useSearchParams(); const mock=params.get('mockState'); const q=useCycles(); const save=useSaveCycle(); const [active,setActive]=useState<string|null>(null); const [editing,setEditing]=useState<DayReward|null>(null); const cycles=mock==='empty'?[]:(q.data??[]); const cycle=cycles.find(c=>c.id===active)??cycles[0]; return <><PageHeader title="Recompensas diarias" subtitle="cada login del jugador escala una recompensa" actions={<><Button icon={<Copy size={14}/>}>duplicar ciclo</Button><Button variant="primary" icon={<Plus size={14}/>}>nuevo ciclo</Button></>}/><div className="mb-7 grid grid-cols-4 gap-4 max-md:grid-cols-2"><StatCard label="racha promedio" value="3.4 días" trend={{value:'+0.8',direction:'up'}}/><StatCard label="completaron 7d" value="12.847"/><StatCard label="XP otorgada" value="+890k"/><StatCard label="ciclos activos" value={cycles.filter(c=>c.active).length}/></div>{mock==='empty'&&cycles.length===0&&<EmptyState title="No hay ciclos" description="Creá un ciclo semanal o mensual."/>}{(mock==='loading'||q.isLoading)&&<Loading label="Cargando recompensas..."/>}{(mock==='error'||q.isError)&&<ErrorState onRetry={()=>q.refetch()}/>} {mock!=='empty'&&mock!=='loading'&&mock!=='error'&&!q.isLoading&&!q.isError&&cycles.length===0&&<EmptyState title="No hay ciclos" description="Creá un ciclo semanal o mensual."/>}{cycle&&<><div className="mb-6 flex gap-1 border-b border-border-subtle">{cycles.map(c=><button key={c.id} onClick={()=>setActive(c.id)} className={`border-b-2 px-4 py-2.5 text-[13px] ${c.id===cycle.id?'border-accent text-accent':'border-transparent text-text-tertiary'}`}>{c.name}</button>)}</div><h3 className="label-section mb-4">Configuración del ciclo "{cycle.name}"</h3><div className="card mb-7 grid grid-cols-3 gap-4 p-5"><input className="field" defaultValue={cycle.name}/><input className="field" type="number" defaultValue={cycle.durationDays}/><select className="field" defaultValue={cycle.resetMode}><option value="on_complete">al completar ciclo</option><option value="on_streak_break">al perder racha</option></select></div><h3 className="label-section mb-4">Recompensas día por día</h3><DaysGrid cycle={cycle} onEdit={setEditing}/><StickyBottomBar onCancel={()=>{}} onSaveDraft={()=>save.mutate({...cycle,active:false})} onActivate={()=>save.mutate({...cycle,active:true})} loading={save.isPending}/></>}<DayEditor day={editing} onClose={()=>setEditing(null)}/></>}
function DaysGrid({cycle,onEdit}:{cycle:RewardsCycle;onEdit:(day:DayReward)=>void}){return <div className="grid grid-cols-7 gap-3 max-[1200px]:grid-cols-4 max-md:grid-cols-2">{cycle.days.map(day=><button key={day.dayNumber} onClick={()=>onEdit(day)} className={`flex min-h-44 flex-col items-center gap-2 rounded-xl border p-4 transition hover:-translate-y-0.5 ${day.isMilestone?'border-gold/40 bg-gradient-to-br from-gold/15 to-warning/10':'border-border-subtle bg-bg-secondary'}`}><span className={`label-section w-full ${day.isMilestone?'text-gold':''}`}>Día {day.dayNumber} {day.isMilestone?'★':''}</span><div className={`flex h-12 w-12 items-center justify-center rounded-full ${day.isMilestone?'bg-gold/20 text-gold':'bg-bg-tertiary text-text-secondary'}`}>{day.isMilestone?<Crown size={20}/>:<Gift size={18}/>}</div>{day.isMilestone&&<p className="text-[10px] font-bold text-gold">¡PREMIO MAYOR!</p>}<ul className="w-full text-[12px] text-text-secondary">{day.rewards.map((r,i)=><li key={i}>+{r.xpAmount??r.coinsAmount??1} {r.type==='xp'?'XP':r.type==='coins'?r.coinId:r.type}</li>)}</ul><span className="mt-auto self-end text-[11px] text-text-tertiary">editar</span></button>)}</div>}
function DayEditor({day,onClose}:{day:DayReward|null;onClose:()=>void}){return <Modal open={!!day} onClose={onClose} title={`Editar día ${day?.dayNumber}`}><div className="space-y-3"><input className="field" defaultValue={day?.rewards[0]?.xpAmount??day?.rewards[0]?.coinsAmount??0}/><Button variant="primary" onClick={onClose}>guardar recompensa</Button></div></Modal>}
