import { Download, MoreVertical, Package, Plus } from 'lucide-react';
import { useState } from 'react';
import { useSearchParams } from 'react-router-dom';
import { Button } from '@/components/ui/Button';
import { EmptyState } from '@/components/ui/EmptyState';
import { ErrorState } from '@/components/ui/ErrorState';
import { FilterPill } from '@/components/ui/FilterPill';
import { IconButton } from '@/components/ui/IconButton';
import { Loading } from '@/components/ui/Loading';
import { Modal } from '@/components/ui/Modal';
import { PageHeader } from '@/components/ui/PageHeader';
import { SearchInput } from '@/components/ui/SearchInput';
import { StatCard } from '@/components/ui/StatCard';
import { Toolbar } from '@/components/ui/Toolbar';
import { ConfiguratorScaffold, ConfigSection } from '@/components/configurator/ConfiguratorScaffold';
import { formatNumber } from '@/lib/format';
import { useProducts, useSaveProduct, useUploadProductImage } from '@/features/tier4Api';
import type { Product, ProductCategory } from '@/types/tier4';
const filters:(ProductCategory|'all'|'sold_out')[]=['all','physical','digital','bonus','sold_out'];
export default function ShopPage(){const [params]=useSearchParams(); const mock=params.get('mockState'); const q=useProducts(); const [filter,setFilter]=useState<ProductCategory|'all'|'sold_out'>('all'); const [editor,setEditor]=useState<Product|null|'new'>(null); const products=mock==='empty'?[]:(q.data??[]); const visible=products.filter(p=>filter==='all'||(filter==='sold_out'?p.status==='sold_out':p.category===filter)); return <><PageHeader title="Tienda virtual" subtitle="productos canjeables por monedas · gestiona tu catálogo y stock" actions={<><Button icon={<Download size={14}/>}>importar</Button><Button variant="primary" icon={<Plus size={14}/>} onClick={()=>setEditor('new')}>nuevo producto</Button></>}/><div className="mb-7 grid grid-cols-4 gap-4 max-md:grid-cols-2"><StatCard label="total productos" value={products.length}/><StatCard label="canjeados 7d" value="1.847" trend={{value:'+12.4%',direction:'up'}}/><StatCard label="revenue 7d" value="847k oro"/><StatCard label="low stock" value={products.filter(isLowStock).length} hint="requieren atención"/></div><Toolbar search={<SearchInput placeholder="buscar producto..."/>} filters={<>{filters.map(f=><FilterPill key={f} label={f==='all'?'todos':f==='sold_out'?'agotados':f} count={f==='all'?products.length:f==='sold_out'?products.filter(p=>p.status==='sold_out').length:products.filter(p=>p.category===f).length} active={filter===f} onClick={()=>setFilter(f)}/>)}</>}/>{(mock==='loading'||q.isLoading)&&<Loading label="Cargando productos..."/>}{(mock==='error'||q.isError)&&<ErrorState onRetry={()=>q.refetch()}/>} {mock!=='loading'&&mock!=='error'&&!q.isLoading&&!q.isError&&products.length===0&&<EmptyState title="No hay productos" description="Agregá un producto canjeable para tu tienda." action={<Button variant="primary" onClick={()=>setEditor('new')}>Crear producto</Button>}/>} {visible.length>0&&<div className="grid grid-cols-4 gap-4 max-[1300px]:grid-cols-3 max-md:grid-cols-1">{visible.map(p=><ProductCard key={p.id} product={p} onEdit={()=>setEditor(p)}/>) }<button onClick={()=>setEditor('new')} className="flex min-h-72 flex-col items-center justify-center rounded-xl border-2 border-dashed border-border-default text-text-tertiary hover:border-accent hover:text-accent"><Plus/><span>agregar producto</span></button></div>}<ProductEditor product={editor} onClose={()=>setEditor(null)}/></>}
function isLowStock(p:Product){return p.stock.kind==='fixed'&&p.stock.remaining<=p.stock.lowThreshold&&p.status!=='sold_out'}
function ProductCard({product,onEdit}:{product:Product;onEdit:()=>void}){const sold=product.status==='sold_out'; const low=isLowStock(product); return <div className={`overflow-hidden rounded-xl border border-border-subtle bg-bg-secondary transition hover:-translate-y-0.5 hover:border-border-default ${sold?'opacity-60':''}`}><div className="relative aspect-square bg-bg-tertiary"><img src={product.imageUrl} alt={product.name} loading="lazy" className="h-full w-full object-cover"/>{sold&&<span className="absolute left-2 top-2 rounded bg-danger/90 px-2 py-0.5 text-[10px] font-semibold text-white">AGOTADO</span>}{low&&<span className="absolute left-2 top-2 rounded bg-warning/90 px-2 py-0.5 text-[10px] font-semibold text-bg-primary">low stock</span>}<div className="absolute right-2 top-2"><IconButton icon={MoreVertical} title="acciones" size="sm"/></div></div><div className="p-3"><div className="label-section mb-1">{product.category}</div><h4 className="line-clamp-2 text-[13px] font-medium">{product.name}</h4><p className="mb-2 line-clamp-2 text-[11px] text-text-tertiary">{product.description}</p><div className="flex items-center justify-between"><span className="text-mono text-[14px] font-semibold text-accent">{formatNumber(product.price.amount)} <span className="text-[11px] text-text-tertiary">{product.price.coinId}</span></span><span className="text-[10px] text-text-tertiary">stock: {product.stock.kind==='unlimited'?'∞':product.stock.remaining}</span></div><Button size="sm" variant="ghost" className="mt-3 w-full" onClick={onEdit}>editar</Button></div></div>}
function ProductEditor({product,onClose}:{product:Product|null|'new';onClose:()=>void}){const open=!!product; const save=useSaveProduct(); const upload=useUploadProductImage(); const initial=product&&product!=='new'?product:null; const [name,setName]=useState(initial?.name??'Nuevo producto QA'); const [fulfillment,setFulfillment]=useState<'auto'|'manual'>(initial?.fulfillment??'auto'); const submit=async()=>{await save.mutateAsync({id:initial?.id,name,description:initial?.description??'producto creado desde BO',category:initial?.category??'digital',imageUrl:initial?.imageUrl??'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=500',price:initial?.price??{amount:500,coinId:'coin_oro'},stock:initial?.stock??{kind:'unlimited'},availability:initial?.availability??{alwaysAvailable:true},fulfillment,redemptionsThisWeek:initial?.redemptionsThisWeek??0,status:initial?.status??'active'});onClose()};return <Modal open={open} onClose={onClose} title={initial?'Editar producto':'Nuevo producto'} description="información, precio, stock, disponibilidad y fulfillment"><ConfiguratorScaffold><ConfigSection title="Información del producto"><input className="field" value={name} onChange={e=>setName(e.target.value)}/><Button onClick={()=>upload.mutate()}>pedir signed URL de imagen</Button></ConfigSection><ConfigSection title="Precio y stock"><input className="field" defaultValue={initial?.price.amount??500}/><select className="field"><option>stock ilimitado</option><option>stock fijo</option></select></ConfigSection><ConfigSection title="Fulfillment"><select className="field" value={fulfillment} onChange={e=>setFulfillment(e.target.value as 'auto'|'manual')}><option value="auto">auto · se otorga al instante</option><option value="manual">manual · operador procesa orden</option></select></ConfigSection><Button variant="primary" loading={save.isPending} onClick={submit}>guardar producto</Button></ConfiguratorScaffold></Modal>}
