export type GameCategory='sports'|'casino'|'live_casino'|'virtuals'|'poker'|'slot_only'|'crash_only'|'bingo_only'|'rng_only'|'other_custom';
export type GameCategoryGroup='primary'|'granular';
export interface CategoryOption{value:GameCategory;label:string;description:string;group:GameCategoryGroup;englobedBy?:GameCategory}
export const CATEGORIES:CategoryOption[]=[{value:'sports',label:'Deportes',description:'sportsbook',group:'primary'},{value:'casino',label:'Casino',description:'engloba slot + crash + bingo + RNG',group:'primary'},{value:'live_casino',label:'Casino en vivo',description:'dealer humano',group:'primary'},{value:'virtuals',label:'Virtuales',description:'partidos virtuales y lotería',group:'primary'},{value:'poker',label:'Poker',description:'todos los formatos',group:'primary'},{value:'slot_only',label:'Slot solo',description:'tragamonedas separado de Casino',group:'granular',englobedBy:'casino'},{value:'crash_only',label:'Crash solo',description:'Aviator, JetX, etc.',group:'granular',englobedBy:'casino'},{value:'bingo_only',label:'Bingo solo',description:'separado de Casino',group:'granular',englobedBy:'casino'},{value:'rng_only',label:'RNG solo',description:'mesas virtuales',group:'granular',englobedBy:'casino'},{value:'other_custom',label:'Otro · custom',description:'categoría libre',group:'granular'}];
export interface OperatorConfig{commercial_name:string;legal_name:string;country:string;website:string;logo_url:string;timezone:string;fiat_currency:string;bo_locale:string;widget_default_locale:string;date_format:'DMY'|'MDY';time_format:'H24'|'H12';first_day_of_week:'monday'|'sunday';daily_reset_policy:'operator_tz'|'player_tz';weekly_reset_policy:'operator_tz'|'player_tz';mission_reset_policy:'operator_tz'|'player_tz';month_end_policy:'calendar'|'rolling_30d';alerts_email:string;reports_email:string;webhook_url?:string;terms_url:string;privacy_url:string;min_player_age:18|21;game_catalog:Record<GameCategory,boolean>}
export type RankingId='best_xp'|'best_casino'|'best_live_casino'|'best_sports'|'best_virtuals'|'best_poker'|'best_depositors'|'best_vip';
export type RankingWindow='daily'|'weekly'|'monthly'|'all_time'; export type RankingVisibility='public'|'vip_only'|'by_country'|'anonymous';
export interface PrizeRow{position_label:string;position_from:number;position_to:number;amount:number;prize_type:'coins'|'coins_plus_chest'|'coins_plus_multiplier'|'xp_boost'}
export interface Ranking{id:RankingId;name:string;description:string;icon:string;metric_label:string;requires_category:GameCategory|null;active:boolean;window:RankingWindow;visibility:RankingVisibility;prizes:PrizeRow[];current_participants:number;total_distributed_this_period:number;closes_at:string}
export interface LeaderboardEntry{position:number;player_handle:string;player_avatar_seed:string;metric_value:number;change:number|null;vip_tier?:'gold'|'silver'|'bronze';verified:boolean}
export type PredictionMarket='result_1x2'|'winner_2options'|'total_goals'|'total_corners'|'both_score'|'exact_score'; export type PredictionEventStatus='active'|'closed_pending_result'|'past'|'draft'; export type Sport='football'|'tennis'|'basketball'|'ufc'|'other';
export interface PredictionMarketDefinition{id:PredictionMarket;label:string;buttons:{value:string;label:string}[]}
export interface PredictionItem{id:string;position:number;name:string;market:PredictionMarket;prize_amount:number;predictions_count:number;predictions_breakdown:{value:string;count:number;percent:number}[];result?:string}
export interface PredictionEvent{id:string;name:string;description:string;sport:Sport;banner_url?:string;status:PredictionEventStatus;closes_at:string;entry_cost:number;items:PredictionItem[];grand_prize_amount:number;grand_prize_chest_id?:string;participants_count:number;pool_accumulated:number;completion_rate:number}
