import { useMemo, useState } from 'react';
import { AlertTriangle, Download } from 'lucide-react';
import { useSearchParams } from 'react-router-dom';
import { Button } from '@/components/ui/Button';
import { EmptyState } from '@/components/ui/EmptyState';
import { ErrorState } from '@/components/ui/ErrorState';
import { Loading } from '@/components/ui/Loading';
import { PageHeader } from '@/components/ui/PageHeader';
import { Table, type Column } from '@/components/ui/Table';
import { formatNumber } from '@/lib/format';
import { useCurve, useDistribution, usePresets, usePublishCurve, useUpdateDraft } from '@/features/levelsApi';
import type { CurvePreset, LevelEntry, LevelsCurve } from '@/types/levels';
import { StickyBottomBar } from '@/features/rules/components/RuleBlocks';
import { toast } from '@/stores/toastStore';
export default function LevelsCurvePage(){const [params]=useSearchParams(); const mock=params.get('mockState'); const q=useCurve(); const presets=usePresets(); const dist=useDistribution(); const update=useUpdateDraft(); const publish=usePublishCurve(); const [draft,setDraft]=useState<LevelsCurve|null>(null); const [scale,setScale]=useState<'linear'|'log'>('linear'); if(mock==='empty')return <EmptyState title="No hay curva configurada" description="Aplicá un preset para crear los 100 niveles iniciales."/>; if(mock==='loading'||q.isLoading)return <Loading label="Cargando curva..."/>; if(mock==='error'||q.isError)return <ErrorState onRetry={()=>q.refetch()}/>; if(!q.data)return <EmptyState title="No hay curva configurada" description="Aplicá un preset para crear los 100 niveles iniciales."/>; const current=draft??q.data; const download=()=>{const blob=new Blob([JSON.stringify(current,null,2)],{type:'application/json'}); const url=URL.createObjectURL(blob); const a=document.createElement('a'); a.href=url; a.download='levels-curve.json'; a.click(); URL.revokeObjectURL(url)}; return <><PageHeader title="Curva de niveles" subtitle="cuánta XP necesita un jugador para alcanzar cada nivel" actions={<Button icon={<Download size={14}/>} onClick={download}>Exportar JSON</Button>}/><div className="mb-5 flex items-start gap-2.5 rounded-lg border border-warning/25 bg-warning/10 p-3"><AlertTriangle size={16} className="mt-0.5 text-warning"/><p className="text-[12px] text-text-secondary">cambiar la curva afecta a <b className="text-text-primary">12,847 jugadores activos</b>. los cambios se aplican solo a XP futura.</p></div><div className="grid grid-cols-[1fr_300px] gap-6 max-[1300px]:grid-cols-1"><main className="space-y-5"><PresetsGrid presets={presets.data??[]} onApply={(preset)=>setDraft(applyFormula(current,preset.formula))}/><CurveChart curve={current} scale={scale} onScaleChange={setScale}/><FormulaCard curve={current} onApply={(formula)=>setDraft(applyFormula(current,formula))}/><LevelsTable curve={current} onChange={(levels)=>setDraft({...current,levels})}/></main><aside className="space-y-4 max-[1300px]:hidden"><CurveAside curve={current} distribution={dist.data??[]}/></aside></div><StickyBottomBar onCancel={()=>setDraft(null)} onSaveDraft={()=>update.mutate(current)} onActivate={()=>publish.mutate(current)} loading={update.isPending||publish.isPending}/></>}
function PresetsGrid({presets,onApply}:{presets:CurvePreset[];onApply:(p:CurvePreset)=>void}){return <div className="card p-5"><div className="mb-4 flex justify-between"><h2 className="section-title">presets</h2><span className="text-[11px] font-light italic text-text-tertiary">elegí un punto de partida</span></div><div className="grid grid-cols-4 gap-3 max-md:grid-cols-2">{presets.map(p=><button key={p.id} onClick={()=>onApply(p)} className="rounded-xl border border-border-subtle bg-bg-tertiary p-4 text-left transition hover:border-accent/30"><div className="mb-3 flex h-14 items-end gap-1">{p.miniChart.map((h,i)=><span key={i} className="flex-1 rounded-t bg-accent/60" style={{height:`${h}%`}}/>)}</div><div className="font-semibold">{p.name}</div><p className="text-[11px] text-text-tertiary">{p.description}</p></button>)}</div></div>}
function CurveChart({curve,scale,onScaleChange}:{curve:LevelsCurve;scale:'linear'|'log';onScaleChange:(s:'linear'|'log')=>void}){const path=useMemo(()=>{const max=Math.max(...curve.levels.map(l=>l.xpRequired)); return curve.levels.map((l,i)=>{const x=30+(l.level-1)/99*740; const value=scale==='log'?Math.log10(l.xpRequired+1)/Math.log10(max+1):l.xpRequired/max; const y=250-value*220; return `${i===0?'M':'L'}${x},${y}`}).join(' ')},[curve,scale]); return <div className="card"><header className="section-head"><h2 className="section-title">curva visual · 100 niveles</h2><div className="flex gap-1"><Button size="sm" variant={scale==='linear'?'secondary':'ghost'} onClick={()=>onScaleChange('linear')}>lineal</Button><Button size="sm" variant={scale==='log'?'secondary':'ghost'} onClick={()=>onScaleChange('log')}>logarítmica</Button></div></header><div className="p-5"><svg viewBox="0 0 800 280" className="h-72 w-full"><defs><linearGradient id="curveFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="var(--accent)" stopOpacity=".25"/><stop offset="100%" stopColor="var(--accent)" stopOpacity="0"/></linearGradient></defs><path d={`${path} L770,250 L30,250 Z`} fill="url(#curveFill)"/><path d={path} fill="none" stroke="var(--accent)" strokeWidth="2"/><path d="M30,250 Q180,242 330,220 T620,115 L770,45" fill="none" stroke="var(--text-tertiary)" strokeDasharray="4 4" opacity=".45"/>{curve.levels.filter(l=>l.isMilestone).map(l=><circle key={l.level} cx={30+(l.level-1)/99*740} cy={250-(l.xpRequired/Math.max(...curve.levels.map(x=>x.xpRequired)))*220} r="4" fill="var(--accent)"/> )}</svg><div className="mt-4 flex gap-6 text-[11px] text-text-tertiary"><span>— curva nueva</span><span>- - curva actual</span><span className="ml-auto font-light italic">pasá el mouse sobre el gráfico para ver detalles</span></div></div></div>}
function FormulaCard({curve,onApply}:{curve:LevelsCurve;onApply:(f:NonNullable<LevelsCurve['formula']>)=>void}){const [base,setBase]=useState(curve.formula?.xpBase??100); const [mult,setMult]=useState(curve.formula?.multiplier??1.15); const [exp,setExp]=useState(curve.formula?.exponent??2.1); return <div className="card p-5"><div className="mb-4"><h2 className="section-title">fórmula matemática</h2><p className="section-help">define la curva con 3 parámetros</p></div><div className="grid grid-cols-3 gap-4"><input className="field" type="number" value={base} onChange={e=>setBase(Number(e.target.value))}/><input className="field" type="number" step="0.01" value={mult} onChange={e=>setMult(Number(e.target.value))}/><input className="field" type="number" step="0.1" value={exp} onChange={e=>setExp(Number(e.target.value))}/></div><div className="mt-4 flex items-center rounded-lg bg-bg-tertiary p-3 font-mono text-[13px]"><span>XP(n) = {base} × {mult}^(n-1) × n^{exp}</span><Button className="ml-auto" size="sm" variant="ghost" onClick={()=>onApply({xpBase:base,multiplier:mult,exponent:exp})}>aplicar →</Button></div></div>}
function LevelsTable({curve,onChange}:{curve:LevelsCurve;onChange:(levels:LevelEntry[])=>void}){const columns:Column<LevelEntry>[]=[{key:'level',header:'nivel',render:l=><span className={l.isMilestone?'text-gold font-semibold':''}>{l.level}{l.isMilestone?'★':''}</span>},{key:'xp',header:'XP requerida',render:l=><input className="field max-w-40" defaultValue={formatNumber(l.xpRequired)} onBlur={(e)=>{const value=Number(e.currentTarget.value.replace(/\D/g,'')); onChange(curve.levels.map(item=>item.level===l.level?{...item,xpRequired:value}:item))}}/>},{key:'delta',header:'delta',render:(l,i)=><span className="text-text-tertiary">{i===0?'—':`+${formatNumber(l.xpRequired-curve.levels[i-1].xpRequired)}`}</span>},{key:'milestone',header:'milestone',render:l=>l.isMilestone?<span className="text-gold">★ milestone</span>:''}]; return <div><div className="mb-3 flex items-center justify-between"><h2 className="section-title">edición granular · 100 niveles</h2><Button size="sm" onClick={()=>toast.info('milestone marcado en la tabla')}>marcar milestone</Button></div><Table columns={columns} rows={curve.levels.slice(0,20).concat(curve.levels.filter(l=>[50,75,100].includes(l.level)))} rowKey={l=>String(l.level)}/><p className="mt-2 text-center text-[12px] font-light italic text-text-tertiary">mostrando niveles clave · la curva completa contiene 100 niveles</p></div>}
function CurveAside({curve,distribution}:{curve:LevelsCurve;distribution:{level:number;count:number}[]}){return <><div className="card p-5"><h3 className="section-title mb-4">resumen</h3><div className="grid gap-3 text-[12px]"><Row label="total niveles" value={String(curve.totalLevels)}/><Row label="XP máxima" value={formatNumber(curve.levels[curve.levels.length-1]?.xpRequired??0,{compact:true})}/><Row label="milestones" value={String(curve.levels.filter(l=>l.isMilestone).length)}/></div></div><div className="card p-5"><h3 className="section-title mb-4">sample players</h3>{distribution.map(d=><Row key={d.level} label={`nivel ${d.level}`} value={formatNumber(d.count)}/>)}</div></>}
function Row({label,value}:{label:string;value:string}){return <div className="flex justify-between border-b border-border-subtle py-2 last:border-0"><span className="text-text-tertiary">{label}</span><b>{value}</b></div>}
function applyFormula(curve:LevelsCurve,formula:NonNullable<LevelsCurve['formula']>):LevelsCurve{const milestones=new Set([5,10,20,50,75,100]); return {...curve,formula,levels:curve.levels.map(l=>({...l,xpRequired:l.level===1?0:Math.round(formula.xpBase*Math.pow(formula.multiplier,l.level-2)*Math.pow(l.level,formula.exponent)),isMilestone:milestones.has(l.level)}))}}
