import { FormProvider, useFieldArray, useForm, useFormContext } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { Plus, Trash2 } from 'lucide-react';
import { useNavigate, useParams } from 'react-router-dom';
import { z } from 'zod';
import { Button } from '@/components/ui/Button';
import { EmptyState } from '@/components/ui/EmptyState';
import { ErrorState } from '@/components/ui/ErrorState';
import { IconButton } from '@/components/ui/IconButton';
import { Loading } from '@/components/ui/Loading';
import { PageHeader } from '@/components/ui/PageHeader';
import { Switch } from '@/components/ui/Switch';
import { useCoins } from '@/features/coinsApi';
import { useMultipliers } from '@/features/multipliersApi';
import { useRule, useSaveRule } from '@/features/rulesApi';
import { Block, BlockConnector, StickyBottomBar } from '../components/RuleBlocks';
const schema=z.object({name:z.string().min(3),description:z.string(),trigger:z.object({event:z.string(),category:z.string()}),conditionsLogic:z.enum(['all','any']),conditions:z.array(z.object({field:z.string(),operator:z.string(),value:z.union([z.string(),z.number(),z.boolean()])})),action:z.object({xpBase:z.coerce.number().min(0),xpMaxPerEvent:z.coerce.number().nullable().optional(),alsoCoins:z.object({amount:z.coerce.number(),currencyId:z.string()}).optional()}),applicableMultiplierIds:z.array(z.string())}); type Values=z.infer<typeof schema>;
export default function RuleEditorPage(){const {id}=useParams(); const isNew=!id||id==='nueva'; const nav=useNavigate(); const q=useRule(isNew?null:id!); const save=useSaveRule(); const form=useForm<Values>({values:q.data as Values|undefined,defaultValues:{name:'Nueva regla de XP',description:'configurá el trigger, condiciones, acción y multiplicadores',trigger:{event:'bet_placed',category:'sports'},conditionsLogic:'all',conditions:[{field:'amount',operator:'gte',value:'5'}],action:{xpBase:50,xpMaxPerEvent:2000,alsoCoins:{amount:10,currencyId:'coin_oro'}},applicableMultiplierIds:['mult_vip_gold']}}); if(!isNew&&q.isLoading)return <Loading label="Cargando regla..."/>; if(q.isError)return <ErrorState onRetry={()=>q.refetch()}/>; const submit=async(status:'draft'|'active')=>{const values=form.getValues(); await save.mutateAsync({id:isNew?null:id!,values:{...(values as any),status}}); nav('/reglas-xp')}; return <FormProvider {...form}><PageHeader title={isNew?'Nueva regla de XP':q.data?.name??'Regla de XP'} subtitle="configurá el trigger, condiciones, acción y multiplicadores" actions={<><Button size="sm" variant="ghost">Duplicar</Button><Button size="sm">Archivar</Button></>}/><div className="grid grid-cols-[1fr_320px] gap-6 max-[1400px]:grid-cols-1"><div><BlockTrigger/><BlockConnector/><BlockConditions/><BlockConnector/><BlockAction/><BlockConnector/><BlockMultipliers/></div><aside className="space-y-4 max-[1400px]:hidden"><PreviewPanel/></aside></div><StickyBottomBar onCancel={()=>nav('/reglas-xp')} onSaveDraft={()=>submit('draft')} onActivate={()=>submit('active')} loading={save.isPending}/></FormProvider>}
function Field({name,label}:{name:keyof Values|'description';label:string}){const {register}=useFormContext<Values>();return <label className="block"><span className="mb-1.5 block text-[12px] text-text-secondary">{label}</span><input className="field" {...register(name as keyof Values)}/></label>}
function BlockTrigger(){const {register}=useFormContext<Values>();return <Block num={1} kind="trigger" kindLabel="cuando · trigger" title="¿qué evento dispara esta regla?"><div className="grid gap-4"><Field name="name" label="nombre"/><Field name="description" label="descripción"/><label><span className="mb-1.5 block text-[12px] text-text-secondary">tipo de evento</span><select className="field" {...register('trigger.event')}><option value="bet_placed">bet_placed · apuesta realizada</option><option value="game_played">game_played · partida jugada</option><option value="deposit">deposit · depósito</option><option value="login">login · inicio de sesión</option></select></label><label><span className="mb-1.5 block text-[12px] text-text-secondary">categoría</span><select className="field" {...register('trigger.category')}><option value="sports">sports · deportes</option><option value="slots">slots</option><option value="poker">poker</option><option value="deposit">deposit</option></select></label></div></Block>}
function BlockConditions(){const {control,register,watch,setValue}=useFormContext<Values>(); const {fields,append,remove}=useFieldArray({control,name:'conditions'}); const logic=watch('conditionsLogic'); return <Block num={2} kind="condition" kindLabel="si · condiciones" title="¿qué condiciones tiene que cumplir?"><div className="mb-4 grid grid-cols-[110px_1fr] gap-3"><select className="field py-1.5 text-[11px]" value={logic} onChange={e=>setValue('conditionsLogic',e.target.value as 'all'|'any')}><option value="all">si TODAS</option><option value="any">si ALGUNA</option></select><p className="text-[11px] font-light italic text-text-tertiary">se {logic==='all'?'cumplen':'cumple alguna de'} estas condiciones</p></div>{fields.map((field,i)=><div key={field.id} className="mb-2 grid grid-cols-[1fr_140px_1fr_36px] gap-2"><input className="field" {...register(`conditions.${i}.field`)}/><select className="field" {...register(`conditions.${i}.operator`)}><option value="eq">es igual a</option><option value="gte">mayor o igual a</option><option value="in">incluye</option></select><input className="field" {...register(`conditions.${i}.value`)}/><IconButton icon={Trash2} title="eliminar" onClick={()=>remove(i)}/></div>)}<Button size="sm" variant="ghost" icon={<Plus size={13}/>} onClick={()=>append({field:'amount',operator:'gte',value:'1'})}>agregar condición</Button></Block>}
function BlockAction(){const {register,watch,setValue}=useFormContext<Values>(); const coins=useCoins(); const also=watch('action.alsoCoins');return <Block num={3} kind="action" kindLabel="entonces · acción" title="¿qué XP otorgar?" active><div className="grid gap-4"><label><span className="mb-1.5 block text-[12px] text-text-secondary">XP base</span><input type="number" className="field" {...register('action.xpBase')}/></label><label><span className="mb-1.5 block text-[12px] text-text-secondary">XP máxima por evento</span><input type="number" className="field" {...register('action.xpMaxPerEvent')}/></label><div className="flex items-center gap-3"><Switch checked={!!also} onChange={(checked)=>setValue('action.alsoCoins',checked?{amount:10,currencyId:'coin_oro'}:undefined)}/><span className="text-[12px] text-text-secondary">también dar monedas</span>{also&&<><input type="number" className="field w-24" {...register('action.alsoCoins.amount')}/><select className="field w-40" {...register('action.alsoCoins.currencyId')}>{coins.data?.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></>}</div></div></Block>}
function BlockMultipliers(){const {watch,setValue}=useFormContext<Values>(); const multipliers=useMultipliers(); const selected=watch('applicableMultiplierIds'); if(multipliers.data?.length===0)return <Block num={4} kind="multiplier" kindLabel="multiplicadores" title="aplicables"><EmptyState title="Sin multiplicadores" description="Creá uno en /multiplicadores"/></Block>; return <Block num={4} kind="multiplier" kindLabel="multiplicadores aplicables" title="¿qué multiplicadores se pueden sumar?"><div className="space-y-2">{multipliers.data?.slice(0,4).map(m=><div key={m.id} className="flex items-center gap-3 rounded-lg border border-border-subtle bg-bg-tertiary p-3"><Switch checked={selected.includes(m.id)} onChange={(checked)=>setValue('applicableMultiplierIds',checked?[...selected,m.id]:selected.filter(id=>id!==m.id))}/><div className="flex-1"><div className="font-medium">{m.name}</div><div className="text-[11px] text-text-tertiary">{m.description}</div></div><span className="text-[16px] font-semibold text-accent">×{m.factor}</span></div>)}</div></Block>}
function PreviewPanel(){const {watch}=useFormContext<Values>(); const values=watch();return <><div className="card p-5"><h3 className="section-title mb-3">vista previa</h3><p className="text-[13px] leading-6 text-text-secondary"><b className="text-accent">Cuando</b> ocurre <b>{values.trigger.event}</b> en <b>{values.trigger.category}</b>, otorgar <b className="text-accent">+{values.action.xpBase} XP</b>{values.action.alsoCoins&&` y ${values.action.alsoCoins.amount} monedas`}.</p></div><div className="card p-5"><h3 className="section-title mb-3">últimos 7 días</h3><div className="grid grid-cols-2 gap-3 text-[12px]"><div><span className="text-text-tertiary">veces aplicada</span><div className="text-[20px] font-semibold">14.238</div></div><div><span className="text-text-tertiary">XP otorgada</span><div className="text-[20px] font-semibold text-accent">847k</div></div></div></div></>}
