import { BarChart3, Bell, Mail, MessageSquare, Plus, Tag } from 'lucide-react';
import { useState } from 'react';
import { useSearchParams } from 'react-router-dom';
import { Button } from '@/components/ui/Button';
import { EmptyState } from '@/components/ui/EmptyState';
import { ErrorState } from '@/components/ui/ErrorState';
import { Loading } from '@/components/ui/Loading';
import { Modal } from '@/components/ui/Modal';
import { PageHeader } from '@/components/ui/PageHeader';
import { Table, type Column } from '@/components/ui/Table';
import { formatNumber } from '@/lib/format';
import { useChannels, useSaveTemplate, useTemplates } from '@/features/tier4Api';
import type { ChannelConfig, ChannelKind, NotificationTemplate } from '@/types/tier4';
const channelMeta:Record<ChannelKind,{name:string;subtitle:string;icon:typeof Bell}>={push:{name:'Push niveles',subtitle:'nativo del SDK · always-on',icon:Bell},email:{name:'Email',subtitle:'vía SendGrid / Mailgun / SES',icon:Mail},sms:{name:'SMS',subtitle:'vía Twilio',icon:MessageSquare},crm:{name:'CRM externo',subtitle:'Braze / Iterable / OneSignal / MoEngage / Klaviyo / HubSpot',icon:Tag}};
export default function NotificationsPage(){const [params]=useSearchParams(); const mock=params.get('mockState'); const channels=useChannels(); const templates=useTemplates(); const [editor,setEditor]=useState(false); const channelRows=mock==='empty'?[]:(channels.data??[]); const templateRows=mock==='empty'?[]:(templates.data??[]); return <><PageHeader title="Notificaciones" subtitle="canales de comunicación con tus jugadores · push nativo, email, SMS o vía tu CRM" actions={<><Button icon={<BarChart3 size={14}/>}>ver métricas</Button><Button variant="primary" icon={<Plus size={14}/>} onClick={()=>setEditor(true)}>nuevo template</Button></>}/>{mock==='empty'&&<><EmptyState title="No hay canales configurados" description="El push nativo aparece siempre conectado cuando hay SDK."/><EmptyState title="No hay templates" description="Creá templates para level up, misiones o broadcasts."/></>}{(mock==='loading'||channels.isLoading||templates.isLoading)&&<Loading label="Cargando notificaciones..."/>}{(mock==='error'||channels.isError||templates.isError)&&<ErrorState onRetry={()=>{channels.refetch();templates.refetch()}}/>}{mock!=='empty'&&mock!=='loading'&&mock!=='error'&&!channels.isLoading&&!templates.isLoading&&<>{channelRows.length===0?<EmptyState title="No hay canales configurados" description="El push nativo aparece siempre conectado cuando hay SDK."/>:<><h2 className="label-section mb-3">Canales</h2><div className="mb-7 grid grid-cols-4 gap-4 max-[1000px]:grid-cols-2 max-md:grid-cols-1">{channelRows.map(c=><ChannelCard key={c.kind} channel={c}/>)}</div></>}{templateRows.length===0?<EmptyState title="No hay templates" description="Creá templates para level up, misiones o broadcasts."/>:<><h2 className="label-section mb-3">Templates de mensajes</h2><TemplatesTable templates={templateRows}/></>}</>}<TemplateEditor open={editor} onClose={()=>setEditor(false)}/></>}
function ChannelCard({channel}:{channel:ChannelConfig}){const meta=channelMeta[channel.kind]; const Icon=meta.icon; const disconnected=channel.status==='disconnected'; return <div className={`rounded-xl border bg-bg-secondary p-5 transition hover:-translate-y-0.5 ${channel.status==='connected'?'border-success/30':channel.status==='warning'?'border-warning/30':'border-border-subtle opacity-80'}`}><div className="mb-4 flex items-start justify-between"><div className="flex h-11 w-11 items-center justify-center rounded-lg bg-bg-tertiary text-text-secondary"><Icon size={20}/></div><span className={`text-[10px] ${channel.status==='connected'?'text-success':channel.status==='warning'?'text-warning':'text-text-tertiary'}`}>{channel.status}</span></div><h3 className="mb-1 text-[14px] font-semibold">{meta.name}</h3><p className="mb-3 text-[11px] text-text-tertiary">{meta.subtitle}</p><p className="mb-3 text-[11px] text-text-secondary">{channel.provider}</p>{channel.warningMessage&&<p className="mb-3 text-[11px] text-warning">⚠ {channel.warningMessage}</p>}<div className="mb-4 flex justify-between text-[11px]"><span className="text-text-tertiary">delivery</span><span className="text-mono text-success">{channel.metric.deliveryRatePercent}%</span></div><Button variant={disconnected?'primary':'secondary'} size="sm" className="w-full">{disconnected?'conectar':'configurar'}</Button></div>}
function TemplatesTable({templates}:{templates:NotificationTemplate[]}){const columns:Column<NotificationTemplate>[]=[{key:'name',header:'nombre',render:t=><div><b>{t.name}</b><div className="text-[11px] text-text-tertiary">{t.content.push?.body??t.content.sms?.body??t.content.email?.subject}</div></div>},{key:'channels',header:'canales',render:t=><div className="flex gap-1">{t.channels.map(c=><span key={c} className="rounded bg-bg-tertiary px-2 py-0.5 text-[10px]">{c}</span>)}</div>},{key:'trigger',header:'trigger',render:t=><span>{t.trigger.kind==='event'?t.trigger.event:'manual'}</span>},{key:'sent',header:'enviados',render:t=><span>{formatNumber(t.sentLast7d)} / 7d</span>},{key:'open',header:'apertura',render:t=><span className="text-success">{t.openRatePercent}%</span>}]; return <Table columns={columns} rows={templates} rowKey={t=>t.id}/>}
function TemplateEditor({open,onClose}:{open:boolean;onClose:()=>void}){const save=useSaveTemplate(); const submit=async()=>{await save.mutateAsync({name:'Template QA broadcast',channels:['push','email'],trigger:{kind:'manual'},content:{push:{title:'Promo',body:'Doble XP hoy'}},active:false,sentLast7d:0,openRatePercent:0}); onClose()};return <Modal open={open} onClose={onClose} title="Nuevo template" description="push, email, SMS o CRM"><div className="space-y-4"><input className="field" defaultValue="Template QA broadcast"/><textarea className="field min-h-24" defaultValue="Doble XP hoy para todos"/><Button variant="primary" loading={save.isPending} onClick={submit}>guardar template</Button></div></Modal>}
