import { ReactNode } from 'react';
import { ChevronDown } from 'lucide-react';
import { cn } from '@/lib/cn';

type Kind = 'trigger' | 'condition' | 'action' | 'multiplier';
const colors: Record<Kind, string> = { trigger:'bg-info/15 text-info border-info/30', condition:'bg-warning/15 text-warning border-warning/30', action:'bg-accent-subtle text-accent border-accent/30', multiplier:'bg-purple/15 text-purple border-purple/30' };
export function Block({num,kind,kindLabel,title,children,active}:{num:number;kind:Kind;kindLabel:string;title:string;children:ReactNode;active?:boolean}){return <div className={cn('rounded-xl border bg-bg-secondary transition',active?'border-accent/40 shadow-glow':'border-border-subtle')}><header className="flex items-center gap-3 border-b border-border-subtle p-4"><div className={cn('flex h-7 w-7 items-center justify-center rounded-lg border text-[13px] font-semibold',colors[kind])}>{num}</div><div><div className="label-section">{kindLabel}</div><div className="text-[13px] font-medium">{title}</div></div></header><div className="p-5">{children}</div></div>}
export function BlockConnector(){return <div className="flex justify-center py-3"><div className="flex h-7 w-7 items-center justify-center rounded-full border border-border-subtle bg-bg-tertiary text-text-tertiary"><ChevronDown size={16}/></div></div>}
export function StickyBottomBar({onCancel,onSaveDraft,onActivate,loading}:{onCancel:()=>void;onSaveDraft:()=>void;onActivate:()=>void;loading?:boolean}){return <div className="sticky bottom-0 z-20 -mx-7 mt-8 flex items-center justify-between border-t border-border-default bg-bg-primary px-7 py-4"><button onClick={onCancel} className="text-[13px] text-text-secondary hover:text-text-primary">← Cancelar</button><div className="flex gap-2"><button onClick={onSaveDraft} disabled={loading} className="rounded-lg border border-border-default bg-bg-tertiary px-3.5 py-2 text-[13px]">Guardar como borrador</button><button onClick={onActivate} disabled={loading} className="rounded-lg bg-accent px-3.5 py-2 text-[13px] font-semibold text-bg-primary">Activar</button></div></div>}
