import { useNavigate, useParams } from 'react-router-dom';
import { FormProvider, useForm } from 'react-hook-form';
import { DayOfWeekSelector } from '@/components/ui/DayOfWeekSelector';
import { PageHeader } from '@/components/ui/PageHeader';
import { ConfiguratorScaffold, ConfigSection } from '@/components/configurator/ConfiguratorScaffold';
import { RewardsBuilder, type RewardsBuilderFormValues } from '@/features/chests/components/RewardsBuilder';
import { StickyBottomBar } from '@/features/rules/components/RuleBlocks';
import { useChest, useSaveChest } from '@/features/tier3Api';
import { useState } from 'react';
export default function ChestEditorPage(){const {id}=useParams(); const isNew=!id||id==='nuevo'; const q=useChest(isNew?null:id!); const save=useSaveChest(); const nav=useNavigate(); const [days,setDays]=useState([5]); const form=useForm<RewardsBuilderFormValues & {name:string;description:string;rarity:string}>({values:q.data as never,defaultValues:{name:'Cofre legendario semanal',description:'Cofre semanal con grandes recompensas',rarity:'legendary',rewards:[{probability:50,type:'coins',label:'100 oro'},{probability:30,type:'coins',label:'500 oro'},{probability:15,type:'xp',label:'1000 XP'},{probability:5,type:'bonus',label:'jackpot'}]}}); const total=(form.watch('rewards')??[]).reduce((s,r)=>s+Number(r.probability||0),0); const submit=async(status:'draft'|'active')=>{if(Math.abs(total-100)>0.01)return; await save.mutateAsync({...q.data,...(form.getValues() as Partial<import('@/types/tier3').Chest>),id:isNew?undefined:id,status,availability:{alwaysAvailable:false,daysOfWeek:days}}); nav('/cofres')};return <FormProvider {...form}><PageHeader title={isNew?'Crear cofre':q.data?.name??'Cofre'} subtitle="configurá un cofre con recompensas aleatorias y probabilidades"/><ConfiguratorScaffold><ConfigSection icon="📦" title="Información básica"><input className="field" {...form.register('name')}/><textarea className="field" {...form.register('description')}/><select className="field" {...form.register('rarity')}><option>common</option><option>rare</option><option>epic</option><option>legendary</option></select></ConfigSection><ConfigSection icon="🎁" title="Recompensas posibles"><RewardsBuilder/></ConfigSection><ConfigSection icon="🔓" title="Cómo se obtiene"><select className="field"><option>compra en tienda · 200 oro</option><option>recompensa de misión</option><option>drop login</option></select></ConfigSection><ConfigSection icon="⏰" title="Disponibilidad"><DayOfWeekSelector value={days} onChange={setDays}/><div className="grid grid-cols-2 gap-3"><input className="field" defaultValue="00:00"/><input className="field" defaultValue="23:59"/></div></ConfigSection></ConfiguratorScaffold><StickyBottomBar onCancel={()=>nav('/cofres')} onSaveDraft={()=>submit('draft')} onActivate={()=>submit('active')} loading={save.isPending}/></FormProvider>}
