import { Plus } from 'lucide-react';
import { useNavigate, useSearchParams } from 'react-router-dom';
import { Button } from '@/components/ui/Button';
import { EmptyState } from '@/components/ui/EmptyState';
import { ErrorState } from '@/components/ui/ErrorState';
import { Loading } from '@/components/ui/Loading';
import { PageHeader } from '@/components/ui/PageHeader';
import { StatCard } from '@/components/ui/StatCard';
import { useChests } from '@/features/tier3Api';
export default function ChestsPage(){const [params]=useSearchParams(); const mock=params.get('mockState'); const q=useChests(); const nav=useNavigate(); const chests=mock==='empty'?[]:(q.data??[]); return <><PageHeader title="Cofres" subtitle="recompensas aleatorias con probabilidades ponderadas" actions={<Button variant="primary" icon={<Plus size={14}/>} onClick={()=>nav('/cofres/nuevo')}>nuevo cofre</Button>}/><div className="mb-7 grid grid-cols-4 gap-4 max-md:grid-cols-2"><StatCard label="cofres activos" value={chests.filter(c=>c.status==='active').length}/><StatCard label="aperturas 7d" value="12.847" trend={{value:'+14%',direction:'up'}}/><StatCard label="EV promedio" value="140 oro"/><StatCard label="legendarios" value={chests.filter(c=>c.rarity==='legendary').length}/></div>{mock==='empty'&&chests.length===0&&<EmptyState title="No hay cofres" description="Creá un cofre con probabilidades que sumen 100%."/>}{(mock==='loading'||q.isLoading)&&<Loading label="Cargando cofres..."/>}{(mock==='error'||q.isError)&&<ErrorState onRetry={()=>q.refetch()}/>} {mock!=='empty'&&mock!=='loading'&&mock!=='error'&&!q.isLoading&&!q.isError&&chests.length===0&&<EmptyState title="No hay cofres" description="Creá un cofre con probabilidades que sumen 100%."/>}<div className="grid grid-cols-3 gap-4 max-md:grid-cols-1">{chests.map(c=><button key={c.id} onClick={()=>nav(`/cofres/${c.id}`)} className="card p-5 text-left hover:border-accent/30"><div className="mb-3 text-[34px]">{c.iconKey}</div><h3 className="font-semibold">{c.name}</h3><p className="text-[12px] text-text-tertiary">{c.description}</p><div className="mt-3 rounded-full bg-warning/15 px-2 py-0.5 text-[11px] text-warning">{c.rarity}</div></button>)}</div></>}
