import { Download } from 'lucide-react';
import { useState } from 'react';
import { useSearchParams } from 'react-router-dom';
import { Button } from '@/components/ui/Button';
import { EmptyState } from '@/components/ui/EmptyState';
import { ErrorState } from '@/components/ui/ErrorState';
import { Loading } from '@/components/ui/Loading';
import { PageHeader } from '@/components/ui/PageHeader';
import { StatCard } from '@/components/ui/StatCard';
import { Table, type Column } from '@/components/ui/Table';
import { formatNumber } from '@/lib/format';
import { useFunnel, useHeatmap, useMetricsKpis, useTopPlayers, useTopRules, useVipDistribution } from '@/features/tier5Api';
import { ActivityHeatmap, FunnelChart, VipDistributionChart } from '../components/MetricsCharts';
const periods=['today','7d','30d','90d'];
export default function MetricsPage(){const [params]=useSearchParams(); const mock=params.get('mockState'); const [period,setPeriod]=useState('7d'); const k=useMetricsKpis(period); const f=useFunnel(period); const vip=useVipDistribution(period); const heat=useHeatmap(period); const rules=useTopRules(period); const players=useTopPlayers(period); const loading=[k,f,vip,heat,rules,players].some(q=>q.isLoading); const error=[k,f,vip,heat,rules,players].some(q=>q.isError); if(mock==='empty')return <EmptyState title="Sin métricas" description="Esperá eventos del operador para ver reportes."/>; return <><PageHeader title="Métricas" subtitle="salud de tu sistema de gamificación · datos en tiempo real" actions={<><div className="inline-flex rounded-lg border border-border-subtle bg-bg-secondary p-0.5">{periods.map(p=><button key={p} onClick={()=>setPeriod(p)} className={`rounded-md px-3 py-1 text-[14px] ${period===p?'bg-bg-tertiary text-text-primary':'text-text-tertiary'}`}>{p}</button>)}</div><Button icon={<Download size={14}/>}>exportar PDF</Button></>}/>{mock==='loading'||loading?<Loading label="Cargando métricas..."/>:null}{(mock==='error'||error)&&<ErrorState onRetry={()=>[k,f,vip,heat,rules,players].forEach(q=>q.refetch())}/>} {mock!=='loading'&&mock!=='error'&&!loading&&!error&&k.data&&<><h2 className="label-section mb-3">KPIs principales</h2><div className="mb-7 grid grid-cols-4 gap-4 max-md:grid-cols-2"><StatCard label="MAU" value={formatNumber(k.data.mau.value)} trend={{value:'+18%',direction:'up'}}/><StatCard label="DAU" value={formatNumber(k.data.dau.value)} trend={{value:'+12%',direction:'up'}}/><StatCard label="stickiness" value={`${k.data.stickiness.value}%`} trend={{value:'+2.1pp',direction:'up'}}/><StatCard label="retention" value={`D7 ${k.data.retention.d7}%`} hint={`D30 ${k.data.retention.d30}%`}/></div><div className="mb-7 grid grid-cols-[2fr_1fr] gap-5 max-[1100px]:grid-cols-1"><FunnelChart steps={f.data??[]}/><VipDistributionChart rows={vip.data??[]}/></div><ActivityHeatmap cells={heat.data??[]}/><div className="mt-7 grid grid-cols-2 gap-5 max-md:grid-cols-1"><TopTable title="Top 5 reglas" rows={rules.data??[]} kind="rules"/><TopTable title="Top 5 jugadores" rows={players.data??[]} kind="players"/></div></>}</>}
function TopTable({title,rows,kind}:{title:string;rows:Array<{id:string;name?:string;handle?:string;count?:number;xp?:number}>;kind:'rules'|'players'}){const cols:Column<(typeof rows)[number]>[]=[{key:'name',header:title,render:(r,i)=><span>{i+1}. {r.name??r.handle}</span>},{key:'value',header:'valor',align:'right',render:r=><b>{formatNumber(r.count??r.xp??0)} {kind==='rules'?'XP':''}</b>}];return <Table columns={cols} rows={rows} rowKey={r=>r.id}/>} 
