import { useNavigate, useParams } from 'react-router-dom';
import { useForm, FormProvider } from 'react-hook-form';
import { PageHeader } from '@/components/ui/PageHeader';
import { ConfiguratorScaffold, ConfigSection } from '@/components/configurator/ConfiguratorScaffold';
import { BlockConditions } from '@/features/rules/components/BlockConditions';
import { StickyBottomBar } from '@/features/rules/components/RuleBlocks';
import { useSaveTournament, useTournament } from '@/features/tier3Api';
import type { Tournament } from '@/types/tier3';
export default function TournamentEditorPage(){const {id}=useParams(); const isNew=!id||id==='nuevo'; const q=useTournament(isNew?null:id!); const save=useSaveTournament(); const nav=useNavigate(); const form=useForm({values:q.data as never,defaultValues:{name:'Liga semanal de slots',description:'Compita esta semana por el premio mayor',conditionsLogic:'all',conditions:[{field:'amount',operator:'gte',value:'1'}],trigger:{event:'xp_earned',category:'slots'},action:{xpBase:0},applicableMultiplierIds:[]}}); const submit=async(status:'draft'|'scheduled')=>{await save.mutateAsync({...q.data,...form.getValues(),id:isNew?undefined:id,status} as Partial<Tournament>);nav('/torneos')};return <FormProvider {...form}><PageHeader title={isNew?'Crear torneo':q.data?.name??'Torneo'} subtitle="configurá un evento competitivo con premios"/><div className="grid grid-cols-[1fr_320px] gap-6 max-[1400px]:grid-cols-1"><ConfiguratorScaffold><ConfigSection icon="🏆" title="Información básica"><input className="field" {...form.register('name')}/><textarea className="field" {...form.register('description')}/></ConfigSection><ConfigSection icon="⚔️" title="Tipo de torneo"><select className="field"><option>leaderboard · top N</option><option>versus</option><option>racha</option></select><BlockConditions/></ConfigSection><ConfigSection icon="📅" title="Fechas"><div className="grid grid-cols-2 gap-3"><input type="datetime-local" className="field"/><input type="datetime-local" className="field"/></div></ConfigSection><ConfigSection icon="💰" title="Prize pool"><div className="grid gap-2"><input className="field" defaultValue="🥇 1° · +5000 XP +2000 oro"/><input className="field" defaultValue="🥈 2° · +3000 XP +1000 oro"/><input className="field" defaultValue="4-10° · +1000 XP"/></div></ConfigSection><ConfigSection icon="🎯" title="Elegibilidad"><select className="field"><option>todos los jugadores</option><option>solo VIP gold+</option><option>segmento específico</option></select></ConfigSection></ConfiguratorScaffold><aside className="card h-fit p-5"><h3 className="section-title mb-3">preview widget</h3><div className="rounded-xl bg-bg-tertiary p-4"><div className="text-3xl">🏆</div><h4 className="font-semibold">{form.watch('name')}</h4><p className="text-[12px] text-text-tertiary">leaderboard · top N · prize pool mixto</p></div></aside></div><StickyBottomBar onCancel={()=>nav('/torneos')} onSaveDraft={()=>submit('draft')} onActivate={()=>submit('scheduled')} loading={save.isPending}/></FormProvider>}
