import { Plus } from 'lucide-react';
import { useNavigate, useSearchParams } from 'react-router-dom';
import { Button } from '@/components/ui/Button';
import { EmptyState } from '@/components/ui/EmptyState';
import { ErrorState } from '@/components/ui/ErrorState';
import { Loading } from '@/components/ui/Loading';
import { PageHeader } from '@/components/ui/PageHeader';
import { StatusPill } from '@/components/ui/StatusPill';
import { useTournaments } from '@/features/tier3Api';
import type { Tournament, TournamentStatus } from '@/types/tier3';
const groups:Record<string,TournamentStatus[]>={"🔴 En vivo ahora":['live'],"📅 Programados":['scheduled','draft'],"✅ Finalizados":['finished','cancelled']};
export default function TournamentsPage(){const [params]=useSearchParams(); const mock=params.get('mockState'); const q=useTournaments(); const nav=useNavigate(); const data=mock==='empty'?[]:(q.data??[]); return <><PageHeader title="Torneos" subtitle="eventos competitivos con premios para tus jugadores" actions={<Button variant="primary" icon={<Plus size={14}/>} onClick={()=>nav('/torneos/nuevo')}>nuevo torneo</Button>}/>{mock==='empty'&&data.length===0&&<EmptyState title="No hay torneos" description="Creá un torneo semanal con leaderboard y premios."/>}{(mock==='loading'||q.isLoading)&&<Loading label="Cargando torneos..."/>}{(mock==='error'||q.isError)&&<ErrorState onRetry={()=>q.refetch()}/>} {mock!=='empty'&&mock!=='loading'&&mock!=='error'&&!q.isLoading&&!q.isError&&data.length===0&&<EmptyState title="No hay torneos" description="Creá un torneo semanal con leaderboard y premios."/>}{data.length>0&&Object.entries(groups).map(([label,statuses])=>{const items=data.filter(t=>statuses.includes(t.status)); if(!items.length)return null; return <section key={label} className="mb-7"><h3 className="label-section mb-3">{label} · {items.length}</h3><div className="grid gap-3">{items.map(t=><TournamentCard key={t.id} tournament={t} onClick={()=>nav(`/torneos/${t.id}`)}/>)}</div></section>})}</>}
function TournamentCard({tournament,onClick}:{tournament:Tournament;onClick:()=>void}){return <button onClick={onClick} className="card grid grid-cols-[1fr_140px_140px] items-center gap-4 p-5 text-left hover:border-accent/30 max-md:grid-cols-1"><div><h3 className="font-semibold">{tournament.iconKey} {tournament.name}</h3><p className="text-[12px] text-text-tertiary">{tournament.description}</p><p className="mt-2 text-[11px] text-text-tertiary">{tournament.participantsCount} participantes · métrica {tournament.metric.event}</p></div><StatusPill status={tournament.status==='live'?'live':tournament.status==='scheduled'?'scheduled':tournament.status==='finished'?'finished':'draft'} label={tournament.status}/><div className="text-[12px] text-text-tertiary">{new Date(tournament.startsAt).toLocaleDateString('es-AR')} → {new Date(tournament.endsAt).toLocaleDateString('es-AR')}</div></button>}
